### ISSUE TITLE
`projectPathSuffix` seems to not resolve

### ISSUE THREAD

**Issue by wiredearp** [per2plex/babel-project-relative-import#2] opened 2016-02-25 15:47 UTC
:beer: In version `0.0.1` on my Ubuntu machine, there's exactly one too many `../` in the resulting path. That's because the source files are in the `src` folder, but `projectPathSuffix` doesn't seem to make a difference here (no matter what bogus filepath I set it to). I use it like this:

```
["babel-project-relative-import", {
    "projectPathSuffix": "src/"
}]
```

**Comment by per2plex** [comment] 2016-02-25 17:25
Which wrapper around Babel are you using or are you using Babel directly? Are you sure the `projectPathSuffix` is getting picked up, because it should definitely make a difference, even when set to a inexistent path?

I'll try to reproduce it on my machine in the mean time :)

**Comment by wiredearp** [comment] 2016-02-25 18:57
I didn't drag my code with me, but I was almost sure my NPM-installed version said `0.0.1`. If you've ever released such a version number, perhaps I just got the old version? I spy a version `1.0.1` now, so I'll try a fresh install tomorrow and report my findings. I use babel-cli directly, by the way, as in `babel src -d build`.

**Comment by wiredearp** [comment] 2016-02-26 09:46
Well, it was version `1.0.0` to begin with, but the bad news is that is still fails with version `1.0.1`. The project in question is on https://github.com/wiredearp/new-spiritual/tree/nogulp (notice branch name `nogulp`). If you `git clone` that, you should be able to say:

```
npm install
npm run build
```

... and it will succeed, but that's only because the import declarations in https://github.com/wiredearp/new-spiritual/blob/nogulp/src/spiritual-gui/src/bundles/Bundle.js have been prefixed with `~/src/` which, according to my calculations, should not be needed with this `projectPathSuffix` set to `src/` in the https://github.com/wiredearp/new-spiritual/blob/nogulp/.babelrc. So it does seem like the config property is not picked up. You will notice that I have nested `src` folders in that project, but it didn't seem to make a difference if I renamed the `src` folders that were nested below the root. Sorry to leave it at your desk like this, I'll debug this myself in due course, but I'm a bit crippled on leisure coding with this whole baby situation going on.

**Comment by per2plex** [comment] 2016-02-26 13:46
Apparently I didn't test it good enough with the babel-cli. I reworked the path normalization and now it works also with relative file paths supplied by the babel-cli (f7c1fb176444a62952c26c4228a1a1f2e2a5e042).

I published a new version, so just reinstalling `babel-project-relative-import` should fix your problem. Tell me if it worked for you, so I can close this issue.

Thanks a lot for reporting this issue, btw :)

**Comment by wiredearp** [comment] 2016-02-26 16:47
:tada: I am happy to report that the issue can be closed. Thanks for the amazingly quick resolution and of course the awesome project itself. If seems like something that should go into the Babel core at some point and perhaps all the way into the specification (somehow). Good job.

**Closed as completed** 2016-02-26 17:00 UTC
